name = "rupiyakamao-worker"
main = "src/index.ts"
compatibility_date = "2023-10-01"

[[d1_databases]]
binding = "DB"
database_name = "rupiyakamao"
database_id = "your-database-id"

[vars]
ENVIRONMENT = "development"
JWT_SECRET = "change-this-to-a-secure-secret-key-in-production"

# OpenAI API configuration (set via wrangler secret)
# Run: wrangler secret put OPENAI_API_KEY
